In [5]:
# !pip install openpyxl
import openpyxl as px

In [2]:
# !pip install numpy pandas
import numpy as np
import pandas as pd

In [6]:
px.utils.range_boundaries(None)

TypeError: expected string or bytes-like object, got 'NoneType'

In [ ]:
a = px.load_workbook('Template/template 1.0.0.xlsx')

In [ ]:
a.defined_names

In [ ]:
import pickle

with open("a.pkl", "rb") as f:
    a = pickle.load(f)

a

In [ ]:
list_NR = list(a.keys())

list_sheets = []
list_ranges = []

for NR in list_NR:
    list_sheets.append(a[NR].attr_text.split("!")[0].replace("'", ""))
    list_ranges.append(a[NR].attr_text.split("!")[1])
n = 0
for rng in list_ranges:
    print(rng)

In [ ]:
for i in range(10):
    print(i)

In [25]:
from openpyxl.utils import range_boundaries

In [14]:
list = [["Belgium"], ["Italy"], [None], [None], [None]]
len(set([item for sublist in list for item in sublist]))

3

In [ ]:
for i in a.defined_names.values():
    print(i.name, i.attr_text)

### Pickles of NRs

In [122]:
a= pd.read_pickle("pickles/df_old_wv.pkl")

In [74]:
a.loc[a["name_ranges"] == "CountryOfEmploymentContractAxis", "cell_values"] = "ciao"
a.loc[a["name_ranges"] == "CountryOfEmploymentContractAxis", "cell_values"].values[0]

'ciao'

In [35]:
list_of_lists = [[1],["january"],[2020]]

list_of_lists[1][0]

'january'

In [166]:
b = pd.read_excel("C:/Users/Andrea.Baschiera/OneDrive - EFRAG/Desktop/wastes.xlsx")
pd.to_pickle(b, "pickles/Mapping_wastes.pkl")

In [165]:
b

,Old,New
0,"01 WASTES RESULTING FROM EXPLORATION, MINING, ...","01 - WASTES RESULTING FROM EXPLORATION, MINING..."
1,0101 Wastes from mineral excavation,01 01 - Wastes from mineral excavation
2,010101 Non-Hazardous Waste - Waste fro...,01 01 01 - Non-Hazardous - Wastes from min...
3,010102 Non-Hazardous Waste - Waste fro...,01 01 02 - Non-Hazardous - Wastes from min...
4,0103 Wastes from further physical and chem...,01 03 - Wastes from physical and chemical pr...
...,...,...
1160,190601 Non-Hazardous Waste - Anaerobic...,NaN
1161,190602 Non-Hazardous Waste - Anaerobic...,NaN
1162,190701 Non-Hazardous Waste - Landfill ...,NaN
1163,190803 Hazardous Waste - Grease and oi...,NaN
1164,190804 Non-Hazardous Waste - Sludges f...,NaN

In [ ]:
list_of_lists = a.loc[a["name_ranges"] == "TypeOfWasteAxis", "cell_values"].values[0]

for i in range(len(list_of_lists)):
    list_of_lists[i] = list_of_lists[i][0]

In [161]:
for i in list_of_lists:
    print(i)

        200101 Non-Hazardous Waste - Paper and cardboard
        160806 Hazardous Waste - Spent liquids used as catalysts
        101102 Non-Hazardous Waste - Waste glass
        150104 Non-Hazardous Waste - Metallic packaging
        040201 Non-Hazardous Waste - Waste from unprocessed textile fibres and other natural fibrous substances mainly of vegetable origin
        040210 Non-Hazardous Waste - Organic matter from natural products (e.g. grease, wax)
        130101 Hazardous Waste - Hydraulic oils, containing PCBs or PCTs
None
None
None
None
None
None
None
None

In [154]:
new_wastes= []
for i in list_of_lists:
    if i is not None:
        if pd.isna(b.loc[b["old"] == i, "new"].values[0]):
            new_wastes.append(["Waste category not present in new Regulation. Please, see https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014D0955"])
        else:
            new_wastes.append([b.loc[b["old"] == i, "new"].values[0]])
   
new_wastes

[['20 01 01  paper and cardboard'],
 ['16 08 06*  spent liquids used as catalysts'],
 ['Waste category not present in new Regulation. Please, see https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014D0955'],
 ['15 01 04  metallic packaging'],
 ['Waste category not present in new Regulation. Please, see https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014D0955'],
 ['04 02 10  organic matter from natural products (for example grease, wax)'],
 ['13 01 01*  hydraulic oils, containing PCBs']]

In [133]:
list_of_lists

['        200101 Non-Hazardous Waste - Paper and cardboard',
 '        160806 Hazardous Waste - Spent liquids used as catalysts',
 '        101102 Non-Hazardous Waste - Waste glass',
 '        150104 Non-Hazardous Waste - Metallic packaging',
 '        040201 Non-Hazardous Waste - Waste from unprocessed textile fibres and other natural fibrous substances mainly of vegetable origin',
 '        040210 Non-Hazardous Waste - Organic matter from natural products (e.g. grease, wax)',
 '        130101 Hazardous Waste - Hydraulic oils, containing PCBs or PCTs',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [126]:
for i in list_of_lists:
    print(i in b["old"].values.tolist())

True
True
True
True
True
True
True
False
False
False
False
False
False
False
False

In [30]:
from openpyxl.utils import range_boundaries
onecell = range_boundaries(a["cell_ranges"][199])
range = range_boundaries(a["cell_ranges"][1])
range

(7, 80, 9, 179)

In [56]:
a = pd.read_pickle("pickles/df_new_wv.pkl")
row = 199
ex = a["cell_values"][1]
ex2 = a["cell_values"][row]

ex2

[[100]]

In [ ]:
from outils.copy_values import check_formula


class shapes(object):
    
    def __init__(self, tuple):
        self.left = tuple[0]
        self.top = tuple[1]
        self.right = tuple[2]
        self.bottom = tuple[3]
        self.rows = self.bottom - self.top + 1
        self.cols = self.right - self.left + 1

    def __str__(self):
        return f"({self.left}, {self.top}, {self.right}, {self.bottom})"
    
    def build_values(self, sheet):

        topleft = sheet.cell(row=self.top, column=self.left)

        if self.isonecell():
            if check_formula(topleft):
                return None
            else:
                return [[topleft.value]]
        else:
            values = []
            found_formula = False

            for row in range(self.rows):
                row_values = []
                for col in range(self.cols):
                    cell = sheet.cell(row=row, column=col)
                    if check_formula(cell):
                        found_formula = True
                        break
                    else:
                        row_values.append(cell.value)
                if found_formula:
                    break
                values.append(row_values)
            return values





shapes1 = shapes(onecell)
shapes2 = shapes(range)

shapes1.rows, shapes1.cols
shapes2.rows, shapes2.cols

shapes1.top

310

In [47]:
a = "ciao"
b = "hello"
list = [1,2,3,45,4]

list[-1].append(a)
list

AttributeError: 'int' object has no attribute 'append'

In [ ]:
class values(object):

    def __init__(self, list_of_lists):
        self.values = list_of_lists
        self.height = lambda: len(self.values) if self.values else 0
        self.width = lambda: len(self.values[0]) if self.values else 0

values_instance = values(ex)
values_instance.height()

40

### Pickles of the cells for which there is no NR

In [ ]:
pd.read_pickle("pickles/missingNR_df.pkl")

pd.read_pickle("pickles/missingNR_df_old_values.pkl")
pd.read_pickle("pickles/missingNR_df_new_wv.pkl")

In [37]:
# loading workbook and accessing NRs as lists
a = load_workbook("Template/VSME-Digital-Template-1.1.0.xlsx", data_only=True)

c:\Users\Andrea.Baschiera\OneDrive - EFRAG\Desktop\Data Migration Tool\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Andrea.Baschiera\OneDrive - EFRAG\Desktop\Data Migration Tool\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [41]:
a["Table of Contents & Validation"].cell(row=3, column=3).fill

<openpyxl.styles.fills.PatternFill object>
Parameters:
patternType='solid', fgColor=<openpyxl.styles.colors.Color object>
Parameters:
rgb=None, indexed=None, auto=None, theme=0, tint=0.0, type='theme', bgColor=<openpyxl.styles.colors.Color object>
Parameters:
rgb=None, indexed=64, auto=None, theme=None, tint=0.0, type='indexed'

In [35]:
cf_rules = a["Table of Contents & Validation"].conditional_formatting

# Iterate over them
for cf_range in cf_rules:
    if str(cf_range) != "<ConditionalFormatting C3>":
        continue
    for rule in cf_rules[cf_range]:
        print(rule.formula)

['$C$3=template_label_incomplete']
['$C$3=template_label_complete']

In [3]:
df_old_wv = pd.read_pickle("pickles/df_old_wv.pkl")
df_old_tomerge = pd.read_pickle("pickles/df_old_tomerge.pkl")
df_new_wv = pd.read_pickle("pickles/df_new_wv.pkl")

len(df_old_wv), len(df_old_tomerge), len(df_new_wv)

(300, 202, 202)

In [9]:
n = 0
for i in range(len(df_new_wv)):
    df_shapes = df_new_wv["cell_shapes"][i]
    if len(df_shapes) == 4:
        print(df_shapes)
        n += 1
    if n == 20:
        break

[4, 450, 4, 549]
[7, 80, 9, 179]
[11, 80, 11, 179]
[10, 80, 10, 179]
[7, 188, 9, 287]
[6, 450, 6, 549]
[3, 29, 4, 128]
[7, 450, 7, 549]
[8, 450, 8, 549]
[3, 435, 3, 534]
[3, 188, 3, 287]
[3, 450, 3, 549]
[3, 336, 3, 435]
[5, 19, 5, 118]
[5, 123, 5, 222]
[5, 226, 5, 325]
[4, 435, 6, 534]
[4, 336, 4, 435]
[5, 29, 8, 128]
[5, 450, 5, 549]

In [16]:
n = 0
for i in range(len(df_new_wv)):
    df_shapes = df_new_wv["cell_shapes"][i]
    df_values = df_new_wv["cell_values"][i]
    if df_values is None:
        continue
    if len(df_shapes) == 4:
        # print(len(df_values))
        print((df_shapes[3]+1 - df_shapes[1]))
        print(df_new_wv["name_ranges"][i])
        # if (df_shapes[3]+1 - df_shapes[1]) > 20:
        #     n += 1
    
# print(f"number of ranges with more than 20 rows: {n}")

100
AddressOfSite
100
AmountOfEmissionToAir
100
AmountOfEmissionToSoil
100
AmountOfEmissionToWater
100
AreaOfSiteInBiodiversitySensitiveArea
100
CityOfSite
100
CountryOfEmploymentContractAxis
100
CountryOfSite
100
IdentifierOfMaterialTypedAxis
100
IdentifierOfSitesInBiodiversitySensitiveAreasTypedAxis
100
IdentifierOfSiteTypedAxis
100
IdentifierOfSubsidiaryTypedAxis
100
ListOfDisclosuresForWhichNoChangesAreReportedComparedToThePreviousPeriodReporting
100
ListOfOmittedDisclosuresDeemedToBeClassifiedOrSensitiveInformation
100
NaceSectorClassificationCodes
100
NameOfMaterialUsed
100
NameOfTheSubsidiary
100
NumberOfEmployeesForCountryOfEmploymentContract
100
PostalCodeOfSite
100
RegisteredAddressOfTheSubsidiary
100
SiteLocatedInABiodiversitySensitiveArea
100
SiteLocatedNearABiodiversitySensitiveArea
1
SustainabilityIssueAddressedByPracticePolicyAndOrFutureInitiative
1
template_reporting_entity_name
1
TotalHazardousWasteGeneratedMass_unit
1
TotalHazardousWasteGeneratedVolume_unit
1
TotalNatureOrientedAreaOffSite
1
TotalNatureOrientedAreaOnSite
1
TotalNonHazardousWasteGeneratedVolume_unit
1
TotalSealedArea
1
TotalUseOfLand
1
TotalWasteGeneratedVolume_unit
100
TotalWasteRecycledReusedAndDirectedToDisposalMass_unit
100
TotalWasteRecycledReusedAndDirectedToDisposalVolume_unit
6
TypeOfContentCoveredByTheCodeOfConductOrHumanRightsPolicyForItsOwnWorkforce
5
TypeOfHumanRightRelatedToTheConfirmedIncident
100
TypeOfPollutantAxis
100
TypeOfWasteAxis
100
VolumeOfMaterialUsed
100
VolumeOfMaterialUsed_unit
100
WasteDirectedToDisposalMass
100
WasteDirectedToDisposalMass_unit
100
WasteDirectedToDisposalVolume
100
WasteDirectedToDisposalVolume_unit
100
WasteDivertedToRecycleOrReuseMass
100
WasteDivertedToRecycleOrReuseMass_unit
100
WasteDivertedToRecycleOrReuseVolume
100
WasteDivertedToRecycleOrReuseVolume_unit
100
WeightOfMaterialUsed
100
WeightOfMaterialUsed_unit

In [ ]:
list_names = a.defined_names.keys()
pyxl_NR = a.defined_names

res = []
for NR in list_names:
    res.append(pyxl_NR[NR].attr_text.split("!")[0].replace("'", ""))

res

In [133]:
df1_filtered = df1[df1["name_ranges"] == "TypeOfPollutantAxis"].iloc[0]
for i in range(len(df1_filtered["cell_values"])):
    df1_filtered["cell_values"][i] = [df1_filtered["cell_values"][i][0]] # taking only first subelement from each sublist

In [134]:
for j in range(df1_filtered["cell_shapes"][3]+1 - df1_filtered["cell_shapes"][1] - len(df1_filtered["cell_values"])):
    df1_filtered["cell_values"].append([None])

In [ ]:
df1_filtered["cell_values"]

In [184]:
filtered = df1[df1['name_ranges'].str.contains('hypercube', case=False, na=False)]

filtered["name_ranges"].values[0]

'BreakdownOfAnnualMassFlowOfRelevantMaterialsUsedByTheUndertakingHypercube'

In [175]:
env = a["Environmental Disclosures"]

for row in range(df1_filtered["cell_shapes"][1], 82):
    env.cell(row=row, column=df1_filtered["cell_shapes"][0]).value = "ciao come" #df1_filtered["cell_values"][row - df1_filtered["cell_shapes"][1]][0]

a.save("Template/debug1.xlsx")

In [4]:
# accessing NRs as lists
all_NRs = a.defined_names
list_NRs = list(a.defined_names.keys())

In [172]:
(4,219) in merged_loc["Environmental Disclosures"].values.tolist()

True

In [165]:
sheet_names = a.sheetnames
merged_loc = pd.DataFrame()

for sheet in sheet_names:
    merged = list(a[sheet].merged_cells.ranges)
    merged_list = []
    for i in range(len(merged)):
        str(merged[i])
        merged_list.append(range_boundaries(str(merged[i]))[:2])
    merged_loc = pd.concat([merged_loc, pd.DataFrame({sheet: merged_list})], axis=1)

In [ ]:
merged = list(a["Environmental Disclosures"].merged_cells.ranges)
merged
# for i in range(len(merged)):
#     print(str(merged[i]))

In [9]:
# Iterating over NRs and accessing their attributes, storing in dict
dict_of_cell_references = {}
for NR in list_NRs:
    dict_of_cell_references[NR] = all_NRs[NR].attr_text.split("!")[1]

In [7]:
def letter_to_number(col):
    col = col.upper()
    n = 0
    for c in col:
        if not ("A" <= c <= "Z"):
            raise ValueError(f"Invalid column letter: {col}")
        n = n * 26 + (ord(c) - ord("A") + 1)
    return n

# examples
letter_to_number("A")   # 1

1

In [ ]:
# Creating shapes of the cell references from ranges
dict_of_cell_shapes = {}
for i in dict_of_cell_references.keys():
    a = dict_of_cell_references[i].split("$")[1:]
    for j in range(len(a)):
        if j % 2 != 1:
            a[j] = letter_to_number(a[j])
    if( len(a) == 4 ):
        a[1] = a[1][:-1]
    dict_of_cell_shapes[i] = a

dict_of_cell_shapes

In [ ]:
df = pd.DataFrame({
    "name_ranges": list_NRs,
    "cell_references": list(dict_of_cell_references.values()),
    "cell_shapes": list(dict_of_cell_shapes.values()),
})
df

In [ ]:
# condition for seeing whether cell reference is a formula
a["Social Disclosures"].cell(row=46, column=4).data_type == "f"  # True

In [4]:
with_data = load_workbook("with_data.xlsx")
empty = load_workbook("empty.xlsx")
NR_old = with_data.defined_names
list_NR_old = list(with_data.defined_names.keys())
NR_new = empty.defined_names
list_NR_new = list(empty.defined_names.keys())

In [8]:
references_old = []
for NR in NR_old:
    references_old.append(NR_old[NR].attr_text.split("!")[1])

shapes_old = []
for i in range(len(list_NR_old)):
    a = references_old[i].split("$")[1:]
    for j in range(len(a)):
        if j % 2 != 1:
            a[j] = letter_to_number(a[j])
    if( len(a) == 4 ):
        a[1] = a[1][:-1]
    a = [int(ciao) for ciao in a]
    shapes_old.append(a)

df_old = pd.DataFrame({
    "name_ranges": list_NR_old,
    "cell_references": references_old,
    "cell_shapes": shapes_old,
})
df_old

  name_ranges cell_references   cell_shapes
0      number            $D$3        [4, 3]
1     number2            $D$5        [4, 5]
2     stringa       $F$3:$F$6  [6, 3, 6, 6]

In [9]:
# Extracting cell values from old workbook based on cell references and shapes

sheet_old = with_data["Sheet1"]

cell_values = []

for i in range(len(df_old)):
    if len(df_old["cell_shapes"][i]) == 2:
        cell_values.append([sheet_old[df_old["cell_references"][i]].value])
    else:
        cell_values_temp = []
        for row in sheet_old.iter_rows( min_row=df_old["cell_shapes"][i][1],
                                        max_row=df_old["cell_shapes"][i][3],
                                        min_col=df_old["cell_shapes"][i][0],
                                        max_col=df_old["cell_shapes"][i][2] ):
            cell_values_temp.append([])
            for col in row:
                cell_values_temp[-1].append(col.value)
        cell_values.append(cell_values_temp)

df_old["cell_values"] = cell_values
df_old

  name_ranges cell_references   cell_shapes                     cell_values
0      number            $D$3        [4, 3]                        [=45+54]
1     number2            $D$5        [4, 5]                       [=number]
2     stringa       $F$3:$F$6  [6, 3, 6, 6]  [[ciao], [come], [va], [ciao]]

In [10]:
references_new = []
for NR in NR_new:
    references_new.append(NR_new[NR].attr_text.split("!")[1])

shapes_new = []
for i in range(len(list_NR_new)):
    a = references_new[i].split("$")[1:]
    for j in range(len(a)):
        if j % 2 != 1:
            a[j] = letter_to_number(a[j])
    if( len(a) == 4 ):
        a[1] = a[1][:-1]
    a = [int(ciao) for ciao in a]
    shapes_new.append(a)

df_new = pd.DataFrame({
    "name_ranges": list_NR_new,
    "cell_references": references_new,
    "cell_shapes": shapes_new,
})
df_new

  name_ranges cell_references    cell_shapes
0      number            $C$7         [3, 7]
1     number2            $O$7        [15, 7]
2     stringa      $H$8:$H$11  [8, 8, 8, 11]

In [11]:
# merging values from old to new (within dataframes)

df_old_tomerge = df_old.iloc[:,[0,3]]
df_new_withvalues = pd.merge(df_new, df_old_tomerge)
df_new_withvalues

  name_ranges cell_references    cell_shapes                     cell_values
0      number            $C$7         [3, 7]                        [=45+54]
1     number2            $O$7        [15, 7]                       [=number]
2     stringa      $H$8:$H$11  [8, 8, 8, 11]  [[ciao], [come], [va], [ciao]]

In [12]:
# paste values into new workbook

sheet_new = empty["Sheet1"]

for i in range(len(df_new_withvalues)):
    if len(df_new_withvalues["cell_shapes"][i]) == 2:
        sheet_new[df_new_withvalues["cell_references"][i]].value = df_new_withvalues["cell_values"][i][0]
    else:
        for row in range( df_new_withvalues["cell_shapes"][i][1],
                                df_new_withvalues["cell_shapes"][i][3] + 1 ):
            for col in range( df_new_withvalues["cell_shapes"][i][0],
                              df_new_withvalues["cell_shapes"][i][2] + 1 ):
                sheet_new.cell(row=row, column=col).value = df_new_withvalues["cell_values"][i][row - df_new_withvalues["cell_shapes"][i][1]][col - df_new_withvalues["cell_shapes"][i][0]]

empty.save("new_with_data.xlsx")

In [ ]:
# avoid shadowing built-in 'list' and use positional indexing to prevent KeyError from non-consecutive DataFrame index
values_list = []
for i in range(len(df)):
    cell_val = df["cell_values"].iloc[i]  # use iloc for positional access
    if isinstance(cell_val, (list, tuple)):
        values_list.append(cell_val[0] if len(cell_val) > 0 else None)
    else:
        values_list.append(cell_val)

len(values_list)

In [ ]:
for i in range(len(df)):
    print(f"value accessed: {df['cell_values'].iloc[i][0]} and df value column: {df['cell_values'].iloc[i]}")

In [53]:
ciao = pd.DataFrame({
    "a": [1,2,3,4,5,6],
    "b": [7,8,9,None,11,12]
})
ciao.iloc[3]["b"]

np.float64(nan)

In [29]:
from openpyxl.utils.cell import range_boundaries

range_string = "A2:H5"

# Get the boundaries
range_boundaries(range_string)

(1, 2, 8, 5)

In [45]:
df1[df1["name_ranges"] == "TypeOfPollutantAxis"]["cell_values"]

173    [[Alachlor, None, None], [Anthracene, None, No...
Name: cell_values, dtype: object

In [8]:
df_thibo = pd.DataFrame({
    "cat1": [1,2,3],
    "cat2": [4,5,6]
})

df2 = pd.DataFrame({
    "keutw": [1,2],
    "ciao": ["thibault", "magro"]
})

df_thibo.merge(df2, left_on="cat1", right_on="keutw", how="left")

   cat1  cat2  keutw      ciao
0     1     4    1.0  thibault
1     2     5    2.0     magro
2     3     6    NaN       NaN

In [ ]:
list_of_sheets = []
list_of_ranges = []

for i in range(len(missingNR_df)):
    list_of_sheets.append(missingNR_df.iloc[:,0].values[i].split("!")[0])
    list_of_ranges.append(missingNR_df.iloc[:,0].values[i].split("!")[1])

In [12]:
list_of_keywords = ["template_", "enum_", "Table", "BreakdownOfEnergyConsumptionAxis", "Hypercube"]

for kw in list_of_keywords:
    df1 = df1[df1["name_ranges"].str.contains(kw) == False]
df1 = df1.reset_index(drop=True)
df1

,name_ranges,sheets,cell_ranges,cell_shapes,cell_values
0,AddressOfSite,General Information,$D$450:$D$549,"[4, 450, 4, 549]","[[Duomo Square], [None], [None], [None], [None..."
1,AmountOfEmissionToAir,Environmental Disclosures,$G$80:$I$179,"[7, 80, 9, 179]","[[567, None, None], [None, None, None], [None,..."
2,AmountOfEmissionToAir_unit,Environmental Disclosures,$C$78,"[3, 78]",[[metric tonnes (t)]]
3,AmountOfEmissionToSoil,Environmental Disclosures,$K$80:$K$179,"[11, 80, 11, 179]","[[None], [67], [None], [None], [None], [None],..."
4,AmountOfEmissionToSoil_unit,Environmental Disclosures,$C$78,"[3, 78]",[[metric tonnes (t)]]
...,...,...,...,...,...
190,WasteDivertedToRecycleOrReuseVolume,Environmental Disclosures,$J$323:$J$422,"[10, 323, 10, 422]","[[1200], [800], [500], [300], [100], [4000], [..."
191,WasteDivertedToRecycleOrReuseVolume_unit,Environmental Disclosures,$G$323:$I$422,"[7, 323, 9, 422]","[[metric tonnes (t), None, None], [kilograms (..."
192,WaterDischargeFromUndertakingProductionProcesses,Environmental Disclosures,$D$310,"[4, 310]",[[100]]
193,WeightOfMaterialUsed,Environmental Disclosures,$G$435:$I$534,"[7, 435, 9, 534]","[[1500, None, None], [800, None, None], [None,..."
194,WeightOfMaterialUsed_unit,Environmental Disclosures,$J$435:$J$534,"[10, 435, 10, 534]","[[kilograms (kg)], [cubic meters (m3)], [None]..."

In [3]:
df1 = pd.read_pickle("df1.pkl")
df1

,name_ranges,sheets,cell_ranges,cell_shapes,cell_values
0,AddressOfSite,General Information,$D$450:$D$549,"[4, 450, 4, 549]","[[Duomo Square], [None], [None], [None], [None..."
1,AmountOfEmissionToAir,Environmental Disclosures,$G$80:$I$179,"[7, 80, 9, 179]","[[567, None, None], [None, None, None], [None,..."
2,AmountOfEmissionToAir_unit,Environmental Disclosures,$C$78,"[3, 78]",[[metric tonnes (t)]]
3,AmountOfEmissionToSoil,Environmental Disclosures,$K$80:$K$179,"[11, 80, 11, 179]","[[None], [67], [None], [None], [None], [None],..."
4,AmountOfEmissionToSoil_unit,Environmental Disclosures,$C$78,"[3, 78]",[[metric tonnes (t)]]
...,...,...,...,...,...
192,WasteDivertedToRecycleOrReuseVolume,Environmental Disclosures,$J$323:$J$422,"[10, 323, 10, 422]","[[1200], [800], [500], [300], [100], [4000], [..."
193,WasteDivertedToRecycleOrReuseVolume_unit,Environmental Disclosures,$G$323:$I$422,"[7, 323, 9, 422]","[[metric tonnes (t), None, None], [kilograms (..."
194,WaterDischargeFromUndertakingProductionProcesses,Environmental Disclosures,$D$310,"[4, 310]",[[100]]
195,WeightOfMaterialUsed,Environmental Disclosures,$G$435:$I$534,"[7, 435, 9, 534]","[[1500, None, None], [800, None, None], [None,..."
196,WeightOfMaterialUsed_unit,Environmental Disclosures,$J$435:$J$534,"[10, 435, 10, 534]","[[kilograms (kg)], [cubic meters (m3)], [None]..."

In [18]:
df[df["name_ranges"].str.contains("Table") == True]

,name_ranges,sheets,cell_ranges,cell_shapes,cell_values
1,AmountOfEmissionsTable,Environmental Disclosures,$D$80:$K$179,"[4, 80, 11, 179]","[[Alachlor, None, None, 567, None, None, None,..."
21,BreakdownOfEnergyConsumptionTable,Environmental Disclosures,$G$12:$K$14,"[7, 12, 11, 14]",None
120,ListOfSitesTable,General Information,$C$450:$H$549,"[3, 450, 8, 549]",None
121,ListOfSubsidiaryTable,General Information,$C$336:$E$435,"[3, 336, 5, 435]","[[1, Company XYZ Subsidiary 1, Street XYZ, Cit..."
127,NumberOfEmployeesForCountryOfEmploymentContrac...,Social Disclosures,$C$29:$H$128,"[3, 29, 8, 128]","[[Italy, None, 140, None, None, None], [Belgiu..."
155,SitesInBiodiversitySensitiveAreasTable,Environmental Disclosures,$C$188:$K$287,"[3, 188, 11, 287]",None

In [ ]:
df["cell_values"].iloc[0].append([None] for)
df["cell_values"].iloc[0]

In [44]:
df[df["name_ranges"] == "RateOfRecordableWorkRelatedAccidentsInTheReportingPeriod"]

,name_ranges,sheets,cell_ranges,cell_shapes,cell_values
142,RateOfRecordableWorkRelatedAccidentsInTheRepor...,Social Disclosures,$D$143,"[4, 143]",None

In [26]:
def month_name_to_number(month_name):
    # Dictionary mapping month names to numbers
    months = {
        "January": 1, "February": 2, "March": 3, "April": 4,
        "May": 5, "June": 6, "July": 7, "August": 8,
        "September": 9, "October": 10, "November": 11, "December": 12
    }
    # Return the corresponding number or None if not found
    return months.get(month_name.capitalize(), None)

print(month_name_to_number("March"))  # Example usage

3

In [28]:
df["cell_values"][0][0][0]

'Duomo Square'

In [22]:
df = pd.read_pickle("pickles/df.pkl")
df

,name_ranges,sheets,cell_ranges,cell_shapes,cell_values
0,AddressOfSite,General Information,$D$450:$D$549,"[4, 450, 4, 549]","[[Duomo Square], [None], [None], [None], [None..."
1,AmountOfEmissionsTable,Environmental Disclosures,$D$80:$K$179,"[4, 80, 11, 179]","[[Alachlor, None, None, 567, None, None, None,..."
2,AmountOfEmissionToAir,Environmental Disclosures,$G$80:$I$179,"[7, 80, 9, 179]","[[567, None, None], [None, None, None], [None,..."
3,AmountOfEmissionToAir_unit,Environmental Disclosures,$C$78,"[3, 78]",[[metric tonnes (t)]]
4,AmountOfEmissionToSoil,Environmental Disclosures,$K$80:$K$179,"[11, 80, 11, 179]","[[None], [67], [None], [None], [None], [None],..."
...,...,...,...,...,...
291,WasteDivertedToRecycleOrReuseVolume,Environmental Disclosures,$J$323:$J$422,"[10, 323, 10, 422]","[[1200], [800], [500], [300], [100], [4000], [..."
292,WasteDivertedToRecycleOrReuseVolume_unit,Environmental Disclosures,$G$323:$I$422,"[7, 323, 9, 422]","[[metric tonnes (t), None, None], [kilograms (..."
293,WaterDischargeFromUndertakingProductionProcesses,Environmental Disclosures,$D$310,"[4, 310]",[[100]]
294,WeightOfMaterialUsed,Environmental Disclosures,$G$435:$I$534,"[7, 435, 9, 534]","[[1500, None, None], [800, None, None], [None,..."
295,WeightOfMaterialUsed_unit,Environmental Disclosures,$J$435:$J$534,"[10, 435, 10, 534]","[[kilograms (kg)], [cubic meters (m3)], [None]..."

In [25]:
df["cell_values"][0]

[['Duomo Square'],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None]]